project_id = "eapbuoqkhckqaswfjexv"

[functions.sync-products-to-stripe]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-song-checkout]
verify_jwt = true

[functions.verify-song-payment]
verify_jwt = false

[functions.update-purchase-status]
verify_jwt = true

[functions.assign-user-role]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.get-all-users]
verify_jwt = true

[functions.send-discord-notification]
verify_jwt = true

[functions.google-auth-start]
verify_jwt = true

[functions.google-auth-callback]
verify_jwt = false

[functions.upload-to-google-drive]
verify_jwt = true
